[package]
name = "voxy-metrics"
description = "Counters, histograms, gauges, timers, and metric registry"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
voxy-shared = { workspace = true }
voxy-config = { workspace = true }
parking_lot = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
