pub mod attention;
pub mod config;
pub mod conversation;
pub mod engine;
pub mod error;
pub mod greeting;
pub mod journey;
pub mod memory;
pub mod micro;
pub mod mission;
pub mod personality;
pub mod presence;
pub mod score;
pub mod silence;
pub mod types;

pub use attention::{ActivityKind, AttentionModel, AttentionState};
pub use config::CompanionConfig;
pub use conversation::ConversationTiming;
pub use engine::CompanionEngine;
pub use error::{CompanionError, Result};
pub use greeting::GreetingEngine;
pub use journey::SharedJourney;
pub use memory::MemoryMoments;
pub use micro::MicroEngine;
pub use mission::MissionCompanion;
pub use personality::CompanionPersonality;
pub use presence::{PresenceSnapshot, PresenceState, PresenceSystem};
pub use score::{PresenceScoreBreakdown, PresenceScoreEngine};
pub use silence::SilenceIntelligence;
pub use types::*;
