use std::time::{Duration, Instant};

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::attention::ActivityKind;

/// Unique identifier for a companion session.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SessionId(pub String);

impl SessionId {
    pub fn new() -> Self {
        Self(uuid::Uuid::new_v4().to_string())
    }
}

impl Default for SessionId {
    fn default() -> Self {
        Self::new()
    }
}

/// User presence signal.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum UserPresence {
    Active,
    Idle { since: DateTime<Utc> },
    Away { since: DateTime<Utc> },
    Sleeping { since: DateTime<Utc> },
    InMeeting,
    Gaming,
    Focused,
    Browsing,
}

impl UserPresence {
    pub fn is_present(&self) -> bool {
        !matches!(self, Self::Away { .. } | Self::Sleeping { .. })
    }
}

/// Time of day context.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TimeContext {
    EarlyMorning,
    Morning,
    Midday,
    Afternoon,
    Evening,
    Night,
    LateNight,
}

impl TimeContext {
    pub fn from_hour(hour: u32) -> Self {
        match hour {
            0..=4 => Self::LateNight,
            5..=7 => Self::EarlyMorning,
            8..=10 => Self::Morning,
            11..=13 => Self::Midday,
            14..=17 => Self::Afternoon,
            18..=20 => Self::Evening,
            21..=22 => Self::Night,
            _ => Self::LateNight,
        }
    }

    pub fn is_work_hours(&self) -> bool {
        matches!(self, Self::Morning | Self::Midday | Self::Afternoon)
    }
}

/// Weather context for greeting variation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum WeatherContext {
    Clear,
    Cloudy,
    Rainy,
    Stormy,
    Snowy,
    Foggy,
    Windy,
    Unknown,
}

/// Emotional expression metadata (NOT actual emotions).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpressionMetadata {
    /// Orb visual state.
    pub orb_state: OrbState,
    /// Interaction energy level (0.0 - 1.0).
    pub energy: f64,
    /// Response urgency hint.
    pub urgency: f64,
    /// Confidence in expression appropriateness.
    pub confidence: f64,
    /// Context tags describing why this expression.
    pub context_tags: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum OrbState {
    Calm,
    Alert,
    Focused,
    Thinking,
    Resting,
    Celebrating,
}

impl OrbState {
    pub fn to_breathing_speed(&self) -> f64 {
        match self {
            Self::Calm => 0.5,
            Self::Alert => 0.8,
            Self::Focused => 0.6,
            Self::Thinking => 0.4,
            Self::Resting => 0.3,
            Self::Celebrating => 0.9,
        }
    }
}

/// Greeting variant generated by the greeting system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Greeting {
    pub text: String,
    pub kind: GreetingKind,
    pub confidence: f64,
    pub context_used: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum GreetingKind {
    Morning,
    Welcome,
    Return,
    PostMission,
    Milestone,
    CheckIn,
}

/// Micro interaction output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MicroInteraction {
    pub text: String,
    pub kind: MicroKind,
    pub confidence: f64,
    pub timing: InteractionTiming,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MicroKind {
    Acknowledgment,
    Progress,
    Completion,
    Encouragement,
    Observation,
    Reminder,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum InteractionTiming {
    Immediate,
    Deferred { delay: Duration },
    NextNaturalPause,
}

/// Mission state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum MissionState {
    Idle,
    Active {
        kind: ActivityKind,
        started_at: DateTime<Utc>,
        description: String,
    },
    Completed {
        kind: ActivityKind,
        started_at: DateTime<Utc>,
        completed_at: DateTime<Utc>,
        summary: String,
    },
}

impl MissionState {
    pub fn is_active(&self) -> bool {
        matches!(self, Self::Active { .. })
    }
}

/// Conversation pacing metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConversationPacing {
    pub thinking_duration: Duration,
    pub response_delay: Duration,
    pub pause_before_speaking: Duration,
    pub estimated_response_length: usize,
    pub topic_complexity: f64,
}

/// Memory reference.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryMoment {
    pub text: String,
    pub kind: MemoryKind,
    pub relevance: f64,
    pub timestamp: DateTime<Utc>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MemoryKind {
    Milestone,
    PastProject,
    UnfinishedWork,
    SharedExperience,
    Achievement,
}

/// The complete output of one companion update cycle.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompanionOutput {
    /// Should we display something?
    pub display: Option<String>,
    /// Expression metadata for visual rendering.
    pub expression: ExpressionMetadata,
    /// Presence score.
    pub presence_score: f64,
    /// Conversation pacing if speaking.
    pub pacing: Option<ConversationPacing>,
    /// Any greeting to show.
    pub greeting: Option<Greeting>,
    /// Any micro interaction.
    pub micro_interaction: Option<MicroInteraction>,
    /// Any memory moment.
    pub memory_moment: Option<MemoryMoment>,
    /// Mission state update.
    pub mission_state: MissionState,
    /// Should we remain silent?
    pub silence: bool,
    /// Update latency in microseconds.
    pub update_latency_us: u64,
}

/// Input to one companion update cycle.
#[derive(Debug, Clone)]
pub struct CompanionInput {
    pub now: DateTime<Utc>,
    pub session_id: SessionId,
    pub user_presence: UserPresence,
    pub current_activity: Option<ActivityKind>,
    pub time_since_last_interaction: Duration,
    pub conversation_count_this_session: usize,
    pub total_session_duration: Duration,
    pub active_goals: Vec<String>,
    pub recent_milestones: Vec<String>,
    pub weather: WeatherContext,
    pub stress_estimate: f64,
    pub idle_duration: Duration,
    pub pending_tasks: usize,
    pub completed_tasks_today: usize,
    pub last_greeting: Option<Instant>,
    pub last_micro_interaction: Option<Instant>,
    pub last_memory_reference: Option<Instant>,
    pub mission_state: MissionState,
    pub focus_level: f64,
}
